version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  reviewers:
  - fabianhinz
  - Miwri
  assignees:
  - fabianhinz
  - Miwri
  labels:
  - dependabot
  ignore:
  - dependency-name: "@types/node"
    versions:
    - 14.14.22
    - 14.14.24
    - 14.14.25
    - 14.14.26
    - 14.14.28
    - 14.14.30
    - 14.14.31
    - 14.14.32
    - 14.14.33
    - 14.14.34
    - 14.14.35
    - 14.14.36
    - 14.14.37
    - 14.14.39
    - 14.14.41
    - 15.0.0
  - dependency-name: algoliasearch
    versions:
    - 4.8.5
    - 4.8.6
    - 4.9.0
  - dependency-name: firebase
    versions:
    - 8.2.10
    - 8.2.4
    - 8.2.5
    - 8.2.6
    - 8.2.7
    - 8.2.8
    - 8.2.9
    - 8.3.0
    - 8.3.1
    - 8.3.2
    - 8.3.3
    - 8.4.0
    - 8.4.1
  - dependency-name: react-dropzone
    versions:
    - 11.2.4
    - 11.3.0
    - 11.3.1
  - dependency-name: mdi-material-ui
    versions:
    - 6.21.0
    - 6.22.0
  - dependency-name: lodash
    versions:
    - 4.17.20
    - 4.17.21
  - dependency-name: "@types/react-dom"
    versions:
    - 17.0.0
    - 17.0.1
  - dependency-name: elliptic
    versions:
    - 6.5.3
    - 6.5.4
  - dependency-name: "@material-ui/core"
    versions:
    - 4.11.3
  - dependency-name: "@material-ui/lab"
    versions:
    - 4.0.0-alpha.57
  - dependency-name: http-proxy
    versions:
    - 1.18.1
- package-ecosystem: npm
  directory: "/functions"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  reviewers:
  - fabianhinz
  - Miwri
  assignees:
  - Miwri
  - fabianhinz
  labels:
  - dependabot
  ignore:
  - dependency-name: algoliasearch
    versions:
    - 4.8.4
    - 4.8.5
    - 4.8.6
    - 4.9.0
  - dependency-name: firebase-admin
    versions:
    - 8.13.0
    - 9.5.0
    - 9.6.0
  - dependency-name: typescript
    versions:
    - 4.1.3
    - 4.1.4
    - 4.1.5
    - 4.2.2
    - 4.2.3
  - dependency-name: "@types/algoliasearch"
    versions:
    - 3.34.11
  - dependency-name: firebase-functions
    versions:
    - 3.13.1
    - 3.13.2
  - dependency-name: lodash
    versions:
    - 4.17.20
